version: '3.8'
services:

  kasa-build:
    build: ./docs
    ports:
      - "8080:80"
    labels:
      - traefik.enable=true
      - traefik.http.routers.kasa-build.rule=Host(`kasa.pradierh.fr`)
      - traefik.http.routers.kasa-build.entrypoints=websecure
      - traefik.http.routers.kasa-build.tls=true
      - traefik.http.routers.kasa-build.tls.certresolver=myresolver
      - traefik.http.services.kasa-build.loadbalancer.server.port=80
    volumes:
      - "./docs:/usr/share/nginx/html"
    container_name: kasa-build
    networks:
      - proxy

  kasa-json:
    build: ./back
    ports:
      - "3000:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.kasa-json.rule=Host(`kasa.pradierh.fr`)
      - traefik.http.routers.kasa-json.entrypoints=websecure
      - traefik.http.routers.kasa-json.tls=true
      - traefik.http.routers.kasa-json.tls.certresolver=myresolver
      - traefik.http.services.kasa-json.loadbalancer.server.port=3000
    volumes:
      - "./back:/app"
      - "/app/node_modules"
    container_name: kasa-json
    networks:
      - proxy

networks:
  proxy:
    external: true